### PR TITLE
record and return total file size in nfs_client_impl

### PR DESCRIPTION
**Pull request by qinzuoyan**
which is useful for printing log when learning

### CODE REVIEW

**Comment by qinzuoyan** [comment]
@imzhenyu , please review it

**Comment by imzhenyu** [comment]
Just find it is the Microsoft repo - down-merged to imzhenyu/rDSN now.

**Comment by qinzuoyan** [comment]
So should we always create pr on imzhenyu/rDSN and then merge to Microsoft, to pass the travis CI?

**Comment by imzhenyu** [comment]
Yes, I did not get the admin privilege of the MS repo yet:-(

**Pull request merged**
