### PR TITLE
fix problem of flush memtables when learning sstables

### PR DESCRIPTION
**Pull request by qinzuoyan**
1. Fix problem of flush memtables when learning sstables.
When learning sstables, we should flush memtables before ApplyLearnState(), because if we install the sstables with memtables not empty, the data in sstables may be newer (with larger sequence number) than data in memtables, which breaks the data layout rule and may make Get() returns obsoleted data.

2. Fix setting start = 0 when learner's state is invalid.
The original code sets start = 1, which would not trigger learner clearing the app.

### CODE REVIEW

**Comment by imzhenyu** [comment]
Nice job:)
For 1, this is a rocksdb specific fix. Do you think it more appropriately to move this logic into rocksdb replication code?
For 2, you mean when the learner state is *in*valid, right?

**Comment by qinzuoyan** [comment]
Thanks for your review.
For 1, you are right, it is more appropriate to move the logic into rocksdb, I'm on doing that.
For 2, yes, it should be invalid.

**Comment by qinzuoyan** [comment]
Updated.
1. move flush memtable logic when learning into rocksdb
2. improve interface comments of replication_app_base

**Comment by imzhenyu** [comment]
Nicely done~

**Pull request merged**
