### PR TITLE
enhance nfs function

### PR DESCRIPTION
**Pull request by lishenglong**
1. add client file cache
2. test file concurrent
3. modify file size type to uint64_t

### CODE REVIEW

**Comment by imzhenyu** [comment]
Comments provided offline; please fix and retry.

**Comment by lishenglong** [comment]
Some modifications:
1. handle file handle open error
2. rename variable name
3. fix client cache, if all the copy requests of the same file are finished, close the file
4. if two user requests try to copy the same file, just skip the duplicated request
5. add client clean timer

**Comment by lishenglong** [comment]
6. clean std::cout

**Comment by imzhenyu** [comment]
Please test use our fault injector to ensure it handles faults appropriately.

**Pull request merged**
