### PR TITLE
fix address name bug & re-generate xxx.types.h

### PR DESCRIPTION
**Pull request by qinzuoyan**
1. fix address name bug, maybe produce an unterminated string when name too long
2. re-generate *.types.h from *.thrift

### CODE REVIEW

**Comment by imzhenyu** [comment]
I see. I forget to fix dsn.thrift. Btw, the name is not really for execution but for logging only, so I would prefer short names to ensure not imposing too much overhead.

**Comment by qinzuoyan** [comment]
I see, I found the unterminated string problem just through the log. On my machine, the host name length exceeds 16, which makes logging hard to understand, so I think 16 maybe too small, and more 32 bytes would not increase too much overhead.

**Comment by imzhenyu** [comment]
u guys have really long machine name:)

**Comment by qinzuoyan** [comment]
Ha, right, not my fault

**Pull request merged**
